### ISSUE TITLE
Unable to add package

### ISSUE THREAD

**Issue by VertofChest** [esnya/InariUdon#27]
Cannot perform upm operation: Unable to add package [ttps://github.com/esnya/InariUdon.git?path=/Packages/com.nekometer.esnya.inari-udon]:
  Package name 'ttps://github.com/esnya/InariUdon.git?path=/Packages/com.nekometer.esnya.inari-udon' is invalid. [InvalidParameter]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by esnya** [comment]
It seems like there might have been a typo in the old document. Please use `https://` instead of `ttps://`.
