### ISSUE TITLE
unable to install package via package manager or via manual install 

### ISSUE THREAD

**Issue by darranis** [esnya/InariUdon#30]
![image_2024-02-16_073548945](https://github.com/esnya/InariUdon/assets/88484429/9736d601-b056-423b-8a4d-56c6e71b553b)

**Comment by darranis** [comment]
also seems to have an issue where it doesn't recognize udon toolkit 1.1.2 installed even after forcing that one into the proper slot in package manager

**Comment by esnya** [comment]
Based on the error messages, it seems that Git has not been installed. You may be able to find more information in the Unity documentation.
